apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper-headless
  namespace: staging
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: kafka-zookeeper
    storage: persistent
