# the headless service is for PetSet DNS, this one is for clients
apiVersion: v1
kind: Service
metadata:  
  name: kafka-zookeeper
  namespace: staging
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: kafka-zookeeper
