{
 "title": "Kafka",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "messages/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\"}",
     "legendFormat": "msg/sec"
    }
   ]
  },
  {
   "title": "Topic BytesIn to BytesOut Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\"}",
     "legendFormat": "in"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\"}",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used"
    }
   ]
  },
  {
   "title": "request metrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\",request=\"Produce\"}",
     "legendFormat": "total time"
    },
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"RequestQueueTimeMs\",request=\"Produce\"}",
     "legendFormat": "queue time"
    }
   ]
  },
  {
   "title": "JVM System CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload"
    }
   ]
  },
  {
   "title": "JVM System Open File Descriptor Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount"
    }
   ]
  },
  {
   "title": "Request Handler Idle (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_oneminuterate",
     "legendFormat": "Idle (%)"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "Total Under Replicated Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Kafka Broker Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    { "expr": "java_lang_runtime_uptime", "legendFormat": "Broker {{ instance }}" }
   ]
  },
  {
   "title": "request queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_value{name=\"RequestQueueSize\",}"
    }
   ]
  },
  {
   "title": "customer topic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_log_log_value{ name=\"LogEndOffset\" , topic = \"customer\" }) - sum(kafka_log_log_value{ name=\"LogStartOffset\", topic = \"customer\" })"
    }
   ]
  },
  {
   "title": "Max lag in messages btw follower and leader replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_value"
    }
   ]
  },
  {
   "title": "customer topic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_log_log_value{ name=\"LogEndOffset\" , topic = \"customer\" }) - sum(kafka_log_log_value{ name=\"LogStartOffset\", topic = \"customer\" })"
    }
   ]
  },
  {
   "title": "Network Processor Idle (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "kafka_network_processor_value" }
   ]
  }
 ]
}